[khan_eunha]
title = "경향신문 ─ 박은하 기자"
url = "https://www.khan.co.kr/reporter_article.html?id=120"
entrySelector = "ul.list_df li"
titleSelector = "strong.tit_thumb.line_clamp3"
linkSelector = "a.link_cont"
contentSelector = "span.lead"
imageSelector = "div.link_thumb img"
waitUntil = "networkidle"

[khan_sungsooh]
title = "경향신문 ─ 홍성수 교수"
url = "https://www.khan.co.kr/reporter_article.html?id=609"
entrySelector = "ul.list_df li"
titleSelector = "strong.tit_thumb.line_clamp3"
linkSelector = "a.link_cont"
contentSelector = "span.lead"
imageSelector = "div.link_thumb img"
waitUntil = "networkidle"

[ohmynews_mongsill]
title = "오마이뉴스 ─ 신필규 시민기자"
url = "http://star.ohmynews.com/NWS_Web/Mobile/i_Room/articles/news_list.aspx?MEM_CD=00701855"
entrySelector = "ul.newest_list li"
titleSelector = "strong.title"
linkSelector = "div.newest_area a.link_today"
contentSelector = "div.category"
imageSelector = "div.image_area img"
waitUntil = "networkidle"

[naver_pariscom]
title = "한국일보 최진주 기자 ─ 네이버 뉴스"
url = "https://media.naver.com/journalist/469/12963"
entrySelector = "ul.press_edit_news_list li.press_edit_news_item.as_thumb"
titleSelector = "span.press_edit_news_title"
linkSelector = "a.press_edit_news_link"
contentSelector = "span.r_ico_b.r_modify"
imageSelector = "span.press_edit_news_thumb img"
waitUntil = "networkidle"

[naver_sisain_uni]
title = "시사인 김연희 기자 ─ 네이버 뉴스"
url = "https://media.naver.com/journalist/308/76099"
entrySelector = "ul.press_edit_news_list li.press_edit_news_item.as_thumb"
titleSelector = "span.press_edit_news_title"
linkSelector = "a.press_edit_news_link"
contentSelector = "span.r_ico_b.r_modify"
imageSelector = "span.press_edit_news_thumb img"
waitUntil = "networkidle"

[naver_sisain_midnightblue]
title = "시사인 김다은 기자 ─ 네이버 뉴스"
url = "https://media.naver.com/journalist/308/76098"
entrySelector = "ul.press_edit_news_list li.press_edit_news_item.as_thumb"
titleSelector = "span.press_edit_news_title"
linkSelector = "a.press_edit_news_link"
contentSelector = "span.r_ico_b.r_modify"
imageSelector = "span.press_edit_news_thumb img"
waitUntil = "networkidle"

[naver_sisain_smile]
title = "시사인 김은지 기자 ─ 네이버 뉴스"
url = "https://media.naver.com/journalist/308/76101"
entrySelector = "ul.press_edit_news_list li.press_edit_news_item.as_thumb"
titleSelector = "span.press_edit_news_title"
linkSelector = "a.press_edit_news_link"
contentSelector = "span.r_ico_b.r_modify"
imageSelector = "span.press_edit_news_thumb img"
waitUntil = "networkidle"
